### ISSUE TITLE
Training time is too long and how to accelerating training？

### ISSUE THREAD

**Issue by ITBeyond1230** [facebookresearch/swav#1]
Hi, a wonderful work and thanks for sharing your code!  Now i run your code on ImageNet following your setting, but I found it takes about one hour and a half for training just one epoch，which is too slow.  So I want to know if I was missing some key points which are import for speeding up training？

**Comment by mathildecaron31** [comment]
Hi, Thanks for your interest in our work. Without much more information it is difficult for me to help you debugging this speed issue. On how many gpus do you train ? Do you use mixed precision ?

**Comment by ITBeyond1230** [comment]
> Hi, Thanks for your interest in our work. Without much more information it is difficult for me to help you debugging this speed issue. On how many gpus do you train ? Do you use mixed precision ?
> I'll include my running times in the READ.me for the different scripts. Hope this will help

Thanks you for kindly reply, and I run the code on 64 V100 GPUs and use the amp mixed precision just following your train scripts in readme. Maybe it's helpful if you could include your running times in the READ.me for the different scripts.

**Comment by mathildecaron31** [comment]
I've included the running times in the READme: on 64GPUs with a batch size of 4096 it should take around 3min40s per epoch.

**Comment by mathildecaron31** [comment]
FYI https://github.com/facebookresearch/swav/commit/9ad22d947a9c8bdf29971598c31aa8300d5859ee
