### ISSUE TITLE
A design problem which may lead model to cheat

### ISSUE THREAD

**Issue by zkmake520** [facebookresearch/swav#15]
Hi
    The algorithm design: view A --> code x, view B ---> code y, then let view B predict code x and view A predicts code y.   
    But in some experiments (CIFAR_10 dataset) , found that, the model will learn to cheat by predicting nearly same embeddings(**z** in paper) for all images including their augmentations.  In this way the loss will decrease rapidly, but model learns wrong.

**Comment by mathildecaron31** [comment]
Hi @zkmake520 ,
That's a very good remark and that is for this reason that we put some constraints on the cluster assignments. See paragraph "Computing codes online" of the paper:

> . This equipartition constraint ensures that the codes for different images in a batch are distinct, thus preventing the trivial solution where every image has the same code.
