### ISSUE TITLE
Choice of dimension of hidden variable

### ISSUE THREAD

**Issue by travishsu** [facebookresearch/swav#17]
Hi, I'm curious about how you choose 2048 as the dimension in the projection layer, it seems that ResNet in this repo will output the tensor with 512 channels. 

If my Resnet has to output tensor with 256 channels, do you think I need to decrease it from 2048?

Thx

**Comment by mathildecaron31** [comment]
Hi, thanks for your interest in this work.

The feature representation of a view corresponds to the output of the final average pooling layer, which has a feature dimension of 2048 for ResNet-50. We choose the hidden layer of the projection head (MLP) to have the same dimensionality as the output of the considered backbone (thus 2048 for RN-50).

Hope that helps
