### ISSUE TITLE
How is it ensured that only full resolution views are used for code computation?

### ISSUE THREAD

**Issue by sayakpaul** [facebookresearch/swav#19]
Referring to this section of the paper:

![image](https://user-images.githubusercontent.com/22957388/91176850-7a887180-e700-11ea-9b72-536c42a7e702.png)

In the code, this part is supposedly handled with `crops_for_assign`:

```python
for i, crop_id in enumerate(args.crops_for_assign):
            with torch.no_grad():
                out = output[bs * crop_id: bs * (crop_id + 1)]

                # time to use the queue
                if queue is not None:
                    if use_the_queue or not torch.all(queue[i, -1, :] == 0):
                        use_the_queue = True
                        out = torch.cat((torch.mm(
                            queue[i],
                            model.module.prototypes.weight.t()
                        ), out))
                    # fill the queue
                    queue[i, bs:] = queue[i, :-bs].clone()
                    queue[i, :bs] = embedding[crop_id * bs: (crop_id + 1) * bs]
                # get assignments
                q = torch.exp(out / args.epsilon).t()
                q = distributed_sinkhorn(q, args.sinkhorn_iterations)[-bs:]
```

I am not sure how this indexing `out = output[bs * crop_id: bs * (crop_id + 1)]` ensures we are only operating on full resolution views (224/160)?

**Comment by ayulockin** [comment]
Also, I feel there is this contradiction. Kindly correct me if I am wrong about this.

Suppose we are considering high resolution(224/160) image for cluster assignment(which makes sense) then we are left with low resolution(96) image. As per this code snippet:

```Python
for v in np.delete(np.arange(np.sum(args.nmb_crops)), crop_id):
   p = softmax(output[bs * v: bs * (v + 1)] / args.temperature)
   subloss -= torch.mean(torch.sum(q * torch.log(p), dim=1))
```

I assume we will then use low resolution for cluster prediction which does not make sense. Will low-resolution view have the same representational ability to predict the cluster which is assigned by the high-resolution view?

**Comment by mathildecaron31** [comment]
@sayakpaul: We define the crops by groups. `nmb_crops`, `size_crops`, `max_scale_crops` and`min_scale_crops` are all lists of the same length given by the number of groups of crops. The crops from a given group share the same properties (i.e. resolution, scale range). `nmb_crops` specifies the number of crops for each group (thus the total number of crops is given by `sum(nmb_crops)`). We attribute an id to each individual crop. For example, with `--nmb_crops 2 6` we define a total of 8 crops (2+6) with ids `0,1,2,3,4,5,6,7`. The crops of the first group are `0` and `1`, and those of the second group are `2`, `3`, `4`, `5`, `6` and `7`.  With `crops_for_assign` you can choose which of these crops are used for computing the cluster assignments. After computing code from crop `crop_id` https://github.com/facebookresearch/swav/blob/fb1b9045a07373575dd4c4996e90235bbdbba694/main_swav.py#L289-L306, all crops except `crop_id` must predict this assignment https://github.com/facebookresearch/swav/blob/fb1b9045a07373575dd4c4996e90235bbdbba694/main_swav.py#L310-L312.


For example, the following sets of arguments are completely equivalent:
* --nmb_crops 2 6 --size_crops 224 96 --min_scale_crops 0.14 0.05 --max_scale_crops 1. 0.14 --crops_for_assign 0 1
* --nmb_crops 6 2 --size_crops 96 224 --min_scale_crops 0.05 0.14 --max_scale_crops 0.14 1. --crops_for_assign 6 7
* --nmb_crops 1 1 1 1 1 1 1 1 --size_crops 224 224 96 96 96 96 96 96 --min_scale_crops 0.14 0.14 0.05 0.05 0.05 0.05 0.05 0.05 --max_scale_crops 1. 1. 0.14 0.14 0.14 0.14 0.14 0.14 --crops_for_assign 0 1
* --nmb_crops 2 2 2 2 --size_crops 224 96 96 96 --min_scale_crops 0.14 0.05 0.05 0.05 --max_scale_crops 1. 0.14 0.14 0.14 --crops_for_assign 0 1

Hope that helps. Please ask further question if this is not clear yet.

**Comment by mathildecaron31** [comment]
@ayulockin:
All crops, except the one used for computing the assignment, have to predict this assignment. In our configuration with 2 large crops and 6 smaller crops, it means that crops 1(large), 2(small), 3(small), 4(small), 5(small), 6(small), and 7(small) predicts the code of crop 0(large), and crops 0(large), 2(small), 3(small), 4(small), 5(small), 6(small), and 7(small) predicts the code of crop 1(large).

**Comment by sayakpaul** [comment]
Thanks @mathildecaron31 for the wonderful explanations. So, going by the terminology used in the paper what's exactly meant by "full resolution crops"?

Also are you ensuring that multi-crop always yields the views in order i.e. a single batch of it would always first contain 2  (batch_size, 224, 224, 3) and 6 (batch_size, 96, 96, 3)? Won't that come in a randomised order?

Apologies if I am sounding dumb.

**Comment by mathildecaron31** [comment]
In the paper, we refer by "full resolution crops" the two larger views.

This line https://github.com/facebookresearch/swav/blob/82bddbb7004ab067e42142a3d024e6346b669e48/src/multicropdataset.py#L59 ensures that the views always come in the same order.

**Comment by sayakpaul** [comment]
Thank you so much @mathildecaron31 :)
