### ISSUE TITLE
Problem about data_path in training code ?

### ISSUE THREAD

**Issue by phecy** [facebookresearch/swav#21]
`main_swav.py` 
the dataset folder is used `args.data_path` which is the path about imagenet dataset root path (contain `train`, `val`, `test`)
```
train_dataset = MultiCropDataset(
        args.data_path,
        args.size_crops,
        args.nmb_crops,
        args.min_scale_crops,
        args.max_scale_crops,
    )
```
`eval_linear.py`
`train_dataset = datasets.ImageFolder(os.path.join(args.data_path, "train"))` 

in `main_swav.py`, if set the `args.data_path=/path/to/imagenet`, it will use the ( `train`, `val`, `test` ) to do self supervised pretraining ,  am i right ?

**Comment by mathildecaron31** [comment]
Hi, we use `train` set only for pre-training so `args.data_path` should point to ImageNet training set (`/path/to/imagenet/train`).

**Comment by mathildecaron31** [comment]
https://github.com/facebookresearch/swav/commit/fb1b9045a07373575dd4c4996e90235bbdbba694
