### ISSUE TITLE
Deepclusterv2: why always freeze the prototypes during training?

### ISSUE THREAD

**Issue by LLLLLLI** [facebookresearch/swav#26]
Hi,
Thanks for your nice work!

I notice in your code that
https://github.com/facebookresearch/swav/blob/82bddbb7004ab067e42142a3d024e6346b669e48/main_deepclusterv2.py#L280
The freeze_prototypes_niters is set to 300000(deepclusterv2_800ep_pretrain.sh) which is equal to 1000 epochs when the batch size is 4096. It seems to never update the parameter of prototypes. I think the prototypes are as same as the fully connected layer in standard classification tasks which should be optimized. So why always freeze them in your code?

**Comment by mathildecaron31** [comment]
Hi,

With deepcluster-v2, the prototypes are learned during k-means clustering. Actually they are set to the centroids learned by k-means (see https://github.com/facebookresearch/swav/blob/82bddbb7004ab067e42142a3d024e6346b669e48/main_deepclusterv2.py#L387).
I tried to fine-tune them during training but this was not giving any improvements.
Hope that helps.
