### ISSUE TITLE
DeepCluster-v2 linear evaluation for fewer epochs

### ISSUE THREAD

**Issue by liuyuyuil** [facebookresearch/swav#29]
Thanks for sharing your code of such a wonderful work. Have you done experiments using DeepCluster-v2 for fewer training epochs, e.g. 100 or 200 epochs ? If so, can you provide the linear evaluation top-1 acc. for such settings? Many thanks.

**Comment by mathildecaron31** [comment]
Thanks for your interest.
I am sorry I have not run these settings.
