### ISSUE TITLE
How to perform multinode training with torch.distributed.launch?

### ISSUE THREAD

**Issue by fangruizhu** [facebookresearch/swav#30]
Hi, nice work! I tried to do pretraining with main_swav.py on multiple machines.

Here's the main code for distributed training.
```
python -m torch.distributed.launch main_swav.py --rank 0 \
--world_size 8 \
--dist_url 'tcp://172.31.11.200:23456' \
```
I comment the line 55-59 in [src/utils.py](https://github.com/facebookresearch/swav/blob/master/src/utils.py) in order to set ranks for each machine. It is okay to run.

But I found that during training, on each machine, only **1** GPU was used. I think it is caused by https://github.com/facebookresearch/swav/blob/77f718581585ae99187d0bdf01899e2de1085c38/src/utils.py#L68. Could you help me figure it out?

Many thanks!

**Comment by mathildecaron31** [comment]
Hi @fangruizhu 

When training main_swav.py on multiple machines I simple launch the sbatch scripts (https://github.com/facebookresearch/swav/blob/master/scripts/swav_800ep_pretrain.sh for example). In this case SLURM automatically create 8 processes per node and I do not use `torch.distributed.launch` utility.

I think you can adapt the code to train on multiple nodes while using `torch.distributed.launch`: I would recommend you to read https://pytorch.org/docs/stable/distributed.html#launch-utility. Reading the "Multi-Node multi-process distributed training: (e.g. two nodes)" paragraph it seems that you should not pass rank or world_size as argument.

Hope that helps

**Comment by mathildecaron31** [comment]
You can also add `print(args.rank)` statement to be sure that each process has a different rank.

**Comment by fangruizhu** [comment]
Thanks:) @mathildecaron31  I fix it with torch multiprocessing package and now it can work fine with multinode training.

**Comment by mathildecaron31** [comment]
Awesome !

**Comment by priyamdey** [comment]
Hi @mathildecaron31 , I had one doubt on the process-to-gpu mapping for the [800ep](https://github.com/facebookresearch/swav/blob/master/scripts/swav_800ep_pretrain.sh?rgh-link-date=2020-10-13T09%3A32%3A35Z) script. As only 8 processes are being spawned per node, each process will serve 8 gpus (as there are 64 gpus in a node). Although I'm aware that multiple process-to-gpu map configurations are possible, how is the batch-size set for such scenarios? In your script, you've set it to 64. Is this per process or per gpu? per process makes it 4096. But isn't batch-size set for gpu?
