### ISSUE TITLE
Deepclusterv2：How to dispaly the results？

### ISSUE THREAD

**Issue by Youngboy12** [facebookresearch/swav#34]
I have used main_deepclusterv2.py train a model on my custom dataset, I want to see the results of cluster. For example, put the images in same class into the same folder. How to do that? Thank you.

**Comment by mathildecaron31** [comment]
Hi @Youngboy12

For example you could dump the `assignments` tensor. https://github.com/facebookresearch/swav/blob/b4aa051475144700d9532a61d9a61654ea236c52/main_deepclusterv2.py#L254 It is a tensor of size "number of clusterings" x "size of the dataset" where `assignments[i][j]` is an `int` that corresponds to the cluster id assigned to instance `j` based on the `i`th clustering.

With this assignment tensor you can easily find all instances belonging to a same cluster.
