### ISSUE TITLE
Pre-trained models (256 batch size, 200 epochs) without multi-crops

### ISSUE THREAD

**Issue by Jiahao000** [facebookresearch/swav#39]
Hi, thanks for your excellent work! Could you kindly release the model and results pre-trained with batch size of 256 for 200 epochs without multi-crops? I am asking because this seems a commonly used configuration in the literature but it is missing both in the paper and the repo. Some researchers also raised this issue before but it seems that it has not be resolved. Due to the limited computing resources, I think releasing this model would help a lot. Thank you very much!

**Comment by mathildecaron31** [comment]
Hi, thanks for your interest. I have not run swav in this setting so I cannot share any checkpoints with you. Multi-crop is one of our contribution and is therefore part of the swav model.
