### ISSUE TITLE
Pre-trained checkpoint for larger architecture?

### ISSUE THREAD

**Issue by jacobswan1** [facebookresearch/swav#4]
Hi! Thanks for the sharing of SWAV! I just wonder that do you have any follow up plans on releasing the pre-trained weight for larger models (like Res50X4, Res152X4), which might provide great help for researchers, as it might be too computational resources demanding for us to re-train it :( 

Again, thanks for your work very much :)

**Comment by mathildecaron31** [comment]
Hi, thanks for your interest ! Yes, that's a fair point, I am planning to upload the larger model checkpoints quickly.

**Comment by mathildecaron31** [comment]
https://github.com/facebookresearch/swav/commit/e9bcd2d38c2fc7390a4c9006b8ff65ce3a463037
