### ISSUE TITLE
Shall we contribute back the lightning implementation

### ISSUE THREAD

**Issue by williamFalcon** [facebookresearch/swav#41]
@mathildecaron31 thanks for the help with the lightning implementation.

Would you like us to submit a PR for it?

**Comment by mathildecaron31** [comment]
Hi @williamFalcon 

Thank you so much for referencing swav in lightning, it was great working with you on that front. I will add the link to the lightning implementation in the README.

 I am not quite sure I understand what you mean ? This repo is only for a minimal reproduction of the swav paper.
