### ISSUE TITLE
SwAV with 100	256	2x224 + 6x96	?

### ISSUE THREAD

**Issue by poodarchu** [facebookresearch/swav#46]
can you provide a model / results of training swav with bs 256, input size 2x224+6x96 for 100 epochs?

The training time is too long.

**Comment by mathildecaron31** [comment]
I haven't run this model. It should run for less than 4 days since each epoch takes ~52min.

**Comment by mathildecaron31** [comment]
Please look at https://github.com/facebookresearch/swav#slow-training if you have speed issue.

**Comment by kaushal-py** [comment]
Hi @poodarchu , were you able to get the results for 100 epochs? Can you let me know the results?
