### ISSUE TITLE
Warning from Training

### ISSUE THREAD

**Issue by GuoleiSun** [facebookresearch/swav#47]
Great work. When I trained the model, in each epoch, it will print a few lines of "Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to ***". I didn't change anything. Is this normal? Thanks

**Comment by mathildecaron31** [comment]
Hi @GuoleiSun 

Thanks for your interest in this work. Yes, it is expected if you're training with mixed precision.
See https://github.com/NVIDIA/apex/issues/318

> Occasionally seeing a message like “overflow detected, skipping step, reducing loss scale” is normal behavior with dynamic loss scaling, and it usually happens in the first few iterations because Amp begins by trying a high loss scale.
