### ISSUE TITLE
Multi-Crop on MoCo

### ISSUE THREAD

**Issue by lihao0374** [facebookresearch/swav#5]
Good job! Thanks for sharing the code. However I was wondering how much gain can Multi-Crop bring on MoCo ? Have you tried it?

**Comment by mathildecaron31** [comment]
Hi ! Thank you for your interest in this work. Multi-crop is a generic data augmentation scheme and can indeed be applied to different methods.

We did try it on SimCLR (cf left of Figure 3 of our arxiv paper: we obtain +2.4 improvement on SimCLR with multi-crop). SimCLR and MoCo are very similar contrastive methods (they have the same loss; the main difference being the provenance of the negative and positive features: current batch in SimCLR and slow network in MoCo). Thus, I believe that similarly to SimCLR, MoCo should benefit from comparing more views with multi-crop.

As multi-crop augmentation is simple to implement (see https://github.com/facebookresearch/swav/blob/2d898a425f2951eafb0c87156bcaf9270f97caf0/src/multicropdataset.py#L19-L62), we hope that researchers will try it on their own methods :) !

**Comment by mseyfi** [comment]
Hi, 
I have a question, how Moco loss would be applied to the 2x6 crops? In your code, you calculate codes only for the full 224 resolutions. However, in moco we do not have codes. Do you simply incorporate all the crops in the loss?

Thanks

**Comment by mathildecaron31** [comment]
Hi @mseyfi ,
I've added in the appendix of our paper (A.8) the details of the loss when using SimCLR and multi-crop. You can adapt that to moco loss since it's very similar.

https://arxiv.org/pdf/2006.09882.pdf
