### ISSUE TITLE
The full Pretrained model with MLP head?

### ISSUE THREAD

**Issue by MaggieWang0614** [facebookresearch/swav#6]

**Comment by MaggieWang0614** [comment]
Hi! Thanks for your valuable open-sourcing! So do you plan to open-source the full pre-trained models (with the MLP head) later? As it might be helpful for researchers to resume and further train the model on the based on SWAV.

Thanks very much!

**Comment by mathildecaron31** [comment]
Hi @MaggieWang0614, thanks for your interest in our work. Ok, that's a fair point, I'll try to release the projection heads and prototype layers shortly.

**Comment by mathildecaron31** [comment]
Done ! You can now find the MLP head and the prototypes in the provided checkpoints. The keys corresponding to the MLP start with `module.projection_head`. The prototypes have the following key: `module.prototypes.weight`.
