### ISSUE TITLE
Question about num_clusters

### ISSUE THREAD

**Issue by ShaoTengLiu** [facebookresearch/swav#64]
Hi, I have  a question about the **num of clusters**.

I understand the num of classes cannot be known, since this is an unsupervised method. However, if we assume we have this information, will it benefit our training? For example, if we know swav will be trained on imagenet and set the num of clusters to 1000 (which is same as the num of classes), will the features become better?

In addition, for dataset like [VisDA17](http://ai.bu.edu/visda-2017/), the num of classes is very small (eg. 12). In this situation, does it make sense for us to still set num_clusters=3000? By the way, I have tried num_clusters=12 or 20 for visda17, but the algorithm became easy to fail.

**Comment by mathildecaron31** [comment]
Hi @ShaoTengLiu 

Thanks for your interest in this work.

On ImageNet we know that the number of classes is 1k but nevertheless the algorithm has better performance with 3k-10k clusters. I would recommend to set the number of cluster one order of magnitude higher than the ground truth number of classes (i.e. 100 in your case).
