### ISSUE TITLE
Question about sinkhorn and Nan

### ISSUE THREAD

**Issue by PLoic** [facebookresearch/swav#67]
Hello @mathildecaron31, first thanks for this works !

I try to adapt Swav method to a different architecture. I have tested on Imagenet with small batch size (e.g. 8, 16) and nmb_prototypes=3000 and epsilon=0.05. The sinkhorn algorithm seems to produce "Nan" caused by the sum of Q which become inf. 

Do you think, that could be caused by the small batch size ?  If not, what could cause this Nan ?

Thanks for your help !

**Comment by PLoic** [comment]
I was doing something wrong in my code. Sorry for the issue.

**Comment by summelon** [comment]
Hi, I am facing the same problem as you.
Would you like to tell me how did you fix it?

**Comment by summelon** [comment]
I found that I missed the l2norm of the output features before multiplying with prototypes.
Everything goes well after I added it.

**Comment by zhangtzq** [comment]
Great, thank you very much!! I tackle the nan loss with l2norm! @summelon
