### ISSUE TITLE
[Question] Tips for fine tuning a pretraining SwAV model

### ISSUE THREAD

**Issue by escorciav** [facebookresearch/swav#68]
Hi @mathildecaron31 , 

are you aware of someone doing "[source/target SSL pretraining](https://arxiv.org/abs/2103.12718)" from a SwAV model?
_Source/Target self-supervision pretraining_ means taking a pre-trained self-supervised model, and fine-tuning using self-supervision on a different dataset.

I'm curious if one should retain the projection layers.

If anyone else is aware please chime in.

Cheers,
Victor

P.D. Thanks for sharing this, and congrats that your work got published and it's receiving attention from others.

**Comment by mathildecaron31** [comment]
Hi @escorciav 

Thanks a lot for your interest and your kind words. No I am not aware of such works unfortunately. That would be interesting, feel free to share updates if you find something interesting.

On a side note, I think it's really worth re-training a SwAV model on data which has a similar domain that the downstream tasks. In-domain SSL pretraining really boosts the performance (for example see Table 3 of our DINO paper https://arxiv.org/abs/2104.14294 where we do SSL pretraining on landmark dataset when considering a landmark retrieval downstream).
