### ISSUE TITLE
Question regarding the license

### ISSUE THREAD

**Issue by fralik** [facebookresearch/swav#7]
Hi!
I wonder if I can use swav internally in a commercial company? We do not charge end-users directly, but of course the company is for profit and it's profit may increase due to usage of DL models.
As the name of the license suggests, I can't use it, but would like to clarify.
Thanks!

**Comment by mathildecaron31** [comment]
Hi @fralik, thanks for your interest. That's indeed something you cannot do due to the current license. We're currently not in a position to change the licensing.
