### ISSUE TITLE
cause some error by nn.BatchNorm1d in self.projection_head.

### ISSUE THREAD

**Issue by suzhenghang** [facebookresearch/swav#8]
SyncBatchNorm.convert_sync_batchnorm() causes ValueError: expected at least 3D input (got 2D input).
how to solve it ?

**Comment by mathildecaron31** [comment]
Hi @suzhenghang, I've had this error a while ago and updating PyTorch from 1.2 to 1.4 fixed it. What PyTorch version are you using (`python -c "import torch; print(torch.__version__)"`) ?

**Comment by suzhenghang** [comment]
Thanks for your reply. The training is ok after updating the torch's version（my torch is 1.3.1）
