### ISSUE TITLE
What's performance in deeper model

### ISSUE THREAD

**Issue by NickChang97** [facebookresearch/swav#80]
Hi, really thanks for sharing your code and model checkpoint. I have noticed that you release wider model based on resnet50, it boost the performance significantly. Did you run on deeper model such as resnet 101 or resnet 152 ?  if you have done this experiment, would you mind sharing this results? thanks in advance.

**Comment by mathildecaron31** [comment]
Hi @NickChang97 

Thanks for your kind words.

Unfortunately I don't have these checkpoints.
