### ISSUE TITLE
Error 404 on  torch.hub.load('facebookresearch/swav', 'resnet50')

### ISSUE THREAD

**Issue by MikaData57** [facebookresearch/swav#86]
I am having a problem loading different zoo models with `Torch.hub.load()`. All tests return a **404 error**. Have you ever encountered this problem?

**Comment by mathildecaron31** [comment]
We changed the name of the main branch of the repo (`master` -> `main`). Can you try again with:
`model = torch.hub.load('facebookresearch/swav:main', 'resnet50')` ?

https://github.com/facebookresearch/swav/commit/06b1b7cbaf6ba2a792300d79c7299db98b93b7f9
