### ISSUE TITLE
Open sourcing imagenet-trained models

### ISSUE THREAD

**Issue by ramprs** [facebookresearch/swav#9]
Thanks for open sourcing your codebase. Would it be possible to share the final model corresponding to Imagenet downstream task that gets 75.3% top-1 accuracy? Thanks in advance

**Comment by mathildecaron31** [comment]
Hi @ramprs, thanks for your interest.
The resnet-50 backbone can be downloaded with the following link: https://dl.fbaipublicfiles.com/deepcluster/swav_800ep_pretrain.pth.tar .
I am not sure to understand your request: would you like me to release the linear classifier (fully connected layer W of dimension 2048x1000) that is trained on top of the frozen backbone ?

**Comment by ramprs** [comment]
Hi @mathildecaron31 , yes exactly. Could you share the linear classifier trained on top of the swav pre-trained resnet-50 backbone? Thanks

**Comment by mathildecaron31** [comment]
https://github.com/facebookresearch/swav/commit/7b93e9f48012a7345a4a63532e97d498a09724ec
